version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TOKEN_SECRET=${TOKEN_SECRET}
      - MAILER_USER=${MAILER_USER}
      - MAILER_PASS=${MAILER_PASS}
      - DOMAIN=${DOMAIN}
      - MONGO_URI=${MONGO_URI}
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: goshikwarkalpak
      MONGO_INITDB_ROOT_PASSWORD: xUA0X769wBchHRzX
